In [29]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

#### load the severity dataset

In [2]:
import pandas as pd
severity_df = pd.read_csv(
    "../data/processed/severity_dataset.csv"
)

severity_df.head()

,age,sex,pregnant,location,travel_history_endemic_area,bed_net_use,irs_spraying,previous_malaria_episodes,fever,chills_rigors,...,platelets_x10e9_l,wbc_x10e9_l,glucose_mg_dl,creatinine_mg_dl,bilirubin_mg_dl,lactate_mmol_l,plasmodium_species,severity,treatment_received,outcome
0,15,F,False,Sub-Saharan Africa - Rural,False,False,True,3,True,True,...,132,5.0,106,0.34,1.5,1.8,P. falciparum,Uncomplicated,True,Recovered
1,21,F,False,Papua New Guinea,False,True,False,2,False,True,...,268,3.8,105,0.76,1.1,1.9,P. vivax,Uncomplicated,True,Recovered
2,13,F,False,Sub-Saharan Africa - Urban,True,True,False,4,True,True,...,128,5.1,86,0.47,1.4,0.8,P. falciparum,Uncomplicated,True,Recovered
3,55,F,False,Solomon Islands,False,False,False,4,True,True,...,324,6.8,85,1.05,1.4,1.1,P. vivax,Uncomplicated,True,Recovered
4,24,F,False,Sub-Saharan Africa - Urban,False,False,False,5,True,True,...,136,6.0,74,0.86,1.9,1.3,P. falciparum,Uncomplicated,True,Recovered

#### check for columns

In [3]:
severity_df.columns

Index(['age', 'sex', 'pregnant', 'location', 'travel_history_endemic_area',
       'bed_net_use', 'irs_spraying', 'previous_malaria_episodes', 'fever',
       'chills_rigors', 'headache', 'night_sweats', 'fatigue_malaise',
       'nausea_vomiting', 'diarrhea', 'cough', 'abdominal_pain', 'jaundice',
       'altered_consciousness', 'seizures', 'hemoglobin_g_dl',
       'platelets_x10e9_l', 'wbc_x10e9_l', 'glucose_mg_dl', 'creatinine_mg_dl',
       'bilirubin_mg_dl', 'lactate_mmol_l', 'plasmodium_species', 'severity',
       'treatment_received', 'outcome'],
      dtype='str')

#### encode severity target

In [4]:
from sklearn.preprocessing import LabelEncoder

le_severity = LabelEncoder()

severity_df["severity"] = le_severity.fit_transform(
    severity_df["severity"]
)

severity_df["severity"].value_counts()

severity
2    796
0    650
1     82
Name: count, dtype: int64

In [5]:
dict(
    zip(
        le_severity.classes_,
        le_severity.transform(
            le_severity.classes_
        )
    )
)

{'Moderate': np.int64(0), 'Severe': np.int64(1), 'Uncomplicated': np.int64(2)}

#### check if any virable create leakage

In [6]:
pd.crosstab(
    severity_df["severity"],
    severity_df["outcome"]
)

outcome   Death  Recovered  Sequelae
severity
0             0        612        38
1            13         49        20
2             0        764        32

#### feature selection for severity
drop "outcome" and "treatment_received" columns as they create leakage

In [7]:
severity_drop_cols = [
    "outcome",
    "treatment_received"
]

#### create final severity dataset

In [8]:
severity_final = severity_df.drop(
    columns=[
        "outcome",
        "treatment_received"
    ]
)

severity_final.shape

(1528, 29)

#### save the severity dataset

In [9]:
severity_final.to_csv(
    "../data/processed/severity_final.csv",
    index=False
)

#### inspect class imbalance

In [10]:
severity_final["severity"].value_counts(normalize=True) * 100

severity
2    52.094241
0    42.539267
1     5.366492
Name: proportion, dtype: float64

#### traim test and split

In [11]:
X = severity_final.drop(
    "severity",
    axis=1
)

y = severity_final["severity"]

In [14]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

### Preprocessing

In [15]:
categorical_cols = [
    "sex",
    "location",
    "plasmodium_species"
]

In [16]:
numeric_cols = [
    col
    for col in X.columns
    if col not in categorical_cols
]

### Models for Severity Prediction

Because of class imbalance, use:

Logistic Regression

In [20]:
from sklearn.linear_model import LogisticRegression

LogisticRegression(
    max_iter=1000,
    class_weight="balanced"
)

LogisticRegression(class_weight='balanced', max_iter=1000)

#### decision tree

In [21]:
from sklearn.tree import DecisionTreeClassifier

DecisionTreeClassifier(
    class_weight="balanced",
    random_state=42
)

DecisionTreeClassifier(class_weight='balanced', random_state=42)

#### random forest

In [23]:
from sklearn.ensemble import RandomForestClassifier

RandomForestClassifier(
    class_weight="balanced",
    random_state=42
)

RandomForestClassifier(class_weight='balanced', random_state=42)

### train the model

In [31]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            StandardScaler(),
            numeric_cols
        ),
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_cols
        )
    ]
)

In [32]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline

rf_model = Pipeline([
    ("preprocessor", preprocessor),
    (
        "classifier",
        RandomForestClassifier(
            n_estimators=200,
            random_state=42,
            class_weight="balanced"
        )
    )
])

rf_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['age', 'pregnant',
                                                   'travel_history_endemic_area',
                                                   'bed_net_use',
                                                   'irs_spraying',
                                                   'previous_malaria_episodes',
                                                   'fever', 'chills_rigors',
                                                   'headache', 'night_sweats',
                                                   'fatigue_malaise',
                                                   'nausea_vomiting',
                                                   'diarrhea', 'cough',
                                                   'abdominal_pain', 'jaundice',
                                                   'altered_consciousness',
                                                   'seizures',
                                                   'hemoglobin_g_dl',
                                                   'platelets_x10e9_l',
                                                   'wbc_x10e9_l',
                                                   'glucose_mg_dl',
                                                   'creatinine_mg_dl',
                                                   'bilirubin_mg_dl',
                                                   'lactate_mmol_l']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['sex', 'location',
                                                   'plasmodium_species'])])),
                ('classifier',
                 RandomForestClassifier(class_weight='balanced',
                                        n_estimators=200, random_state=42))])

### generate prediction

In [33]:
y_pred = rf_model.predict(X_test)

#### verify prediction

In [34]:
y_pred[:10]

array([2, 2, 0, 0, 2, 1, 0, 2, 2, 0])

### calculate metrix

In [35]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

print(
    "Accuracy:",
    accuracy_score(y_test, y_pred)
)

print(
    "Precision:",
    precision_score(
        y_test,
        y_pred,
        average="weighted"
    )
)

print(
    "Recall:",
    recall_score(
        y_test,
        y_pred,
        average="weighted"
    )
)

print(
    "F1:",
    f1_score(
        y_test,
        y_pred,
        average="weighted"
    )
)

Accuracy: 0.9281045751633987
Precision: 0.9368432455855269
Recall: 0.9281045751633987
F1: 0.927107705827429

In [36]:
from sklearn.metrics import classification_report

print(
    classification_report(
        y_test,
        y_pred
    )
)

              precision    recall  f1-score   support

           0       1.00      0.83      0.91       130
           1       1.00      1.00      1.00        17
           2       0.88      1.00      0.94       159

    accuracy                           0.93       306
   macro avg       0.96      0.94      0.95       306
weighted avg       0.94      0.93      0.93       306

In [38]:
import pandas as pd

df = pd.read_csv("../data/processed/diagnosis_final.csv")

In [39]:
df.groupby("diagnosis")["bilirubin_mg_dl"].describe()

            count      mean       std  min  25%  50%  75%  max
diagnosis
0          1528.0  1.708573  1.074177  0.5  1.2  1.5  1.9  8.5
1          3472.0  0.650029  0.210431  0.3  0.5  0.7  0.8  1.0

In [41]:
import joblib

joblib.dump(
    rf_model,
    "../models/malaria_severity_rf.pkl"
)

['../models/malaria_severity_rf.pkl']