#### imports

In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import classification_report

#### load the diagnosis final result data

In [3]:
df = pd.read_csv("../data/processed/diagnosis_final.csv")

df.head()

,age,sex,pregnant,location,travel_history_endemic_area,bed_net_use,irs_spraying,previous_malaria_episodes,fever,chills_rigors,...,altered_consciousness,seizures,hemoglobin_g_dl,platelets_x10e9_l,wbc_x10e9_l,glucose_mg_dl,creatinine_mg_dl,bilirubin_mg_dl,lactate_mmol_l,diagnosis
0,15,F,False,Sub-Saharan Africa - Rural,False,False,True,3,True,True,...,False,False,10.6,132,5.0,106,0.34,1.5,1.8,0
1,27,F,False,Latin America - Urban,False,False,False,0,False,False,...,False,False,14.1,360,8.7,80,0.73,1.0,1.8,1
2,21,F,False,Papua New Guinea,False,True,False,2,False,True,...,False,False,10.1,268,3.8,105,0.76,1.1,1.9,0
3,17,F,False,Southeast Asia - Rural,False,True,True,2,False,False,...,False,False,13.6,216,9.2,99,0.40,0.5,2.0,1
4,13,F,False,Sub-Saharan Africa - Urban,True,True,False,4,True,True,...,False,False,13.5,128,5.1,86,0.47,1.4,0.8,0

#### split te data

In [4]:
X = df.drop("diagnosis", axis=1)
y = df["diagnosis"]

#### train test split

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(X_train.shape)
print(X_test.shape)

(4000, 27)
(1000, 27)

#### identify columns

In [6]:
X.dtypes

age                              int64
sex                                str
pregnant                          bool
location                           str
travel_history_endemic_area       bool
bed_net_use                       bool
irs_spraying                      bool
previous_malaria_episodes        int64
fever                             bool
chills_rigors                     bool
headache                          bool
night_sweats                      bool
fatigue_malaise                   bool
nausea_vomiting                   bool
diarrhea                          bool
cough                             bool
abdominal_pain                    bool
jaundice                          bool
altered_consciousness             bool
seizures                          bool
hemoglobin_g_dl                float64
platelets_x10e9_l                int64
wbc_x10e9_l                    float64
glucose_mg_dl                    int64
creatinine_mg_dl               float64
bilirubin_mg_dl                float64
lactate_mmol_l                 float64
dtype: object

In [7]:
categorical_cols = [
    "sex",
    "location"
]

In [8]:
numeric_cols = [
    col for col in X.columns
    if col not in categorical_cols
]

#### create preprocessor

In [9]:
preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_cols
        )
    ],
    remainder="passthrough"
)

In [10]:
print(preprocessor)

ColumnTransformer(remainder='passthrough',
                  transformers=[('cat', OneHotEncoder(handle_unknown='ignore'),
                                 ['sex', 'location'])])

#### pipeline

In [11]:
rf_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    (
        "classifier",
        RandomForestClassifier(
            random_state=42
        )
    )
])

In [12]:
rf_pipeline

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['sex', 'location'])])),
                ('classifier', RandomForestClassifier(random_state=42))])

In [14]:
print(X_train.shape)
print(X_test.shape)
print(X.columns.tolist())

(4000, 27)
(1000, 27)
['age', 'sex', 'pregnant', 'location', 'travel_history_endemic_area', 'bed_net_use', 'irs_spraying', 'previous_malaria_episodes', 'fever', 'chills_rigors', 'headache', 'night_sweats', 'fatigue_malaise', 'nausea_vomiting', 'diarrhea', 'cough', 'abdominal_pain', 'jaundice', 'altered_consciousness', 'seizures', 'hemoglobin_g_dl', 'platelets_x10e9_l', 'wbc_x10e9_l', 'glucose_mg_dl', 'creatinine_mg_dl', 'bilirubin_mg_dl', 'lactate_mmol_l']

#### create random forest baseline

In [15]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

baseline_model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier(
        random_state=42
    ))
])

baseline_model.fit(X_train, y_train)

y_pred = baseline_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1:", f1_score(y_test, y_pred))

Accuracy: 0.993
Precision: 0.9900142653352354
Recall: 1.0
F1: 0.9949820788530466

## Hyperparameter Tuning
#### parameter grid

In [16]:
param_grid = {
    "classifier__n_estimators": [100, 200, 300, 500],
    "classifier__max_depth": [None, 5, 10, 20, 30],
    "classifier__min_samples_split": [2, 5, 10],
    "classifier__min_samples_leaf": [1, 2, 4],
    "classifier__max_features": ["sqrt", "log2"]
}

#### random search

In [17]:
random_search = RandomizedSearchCV(
    estimator=rf_pipeline,
    param_distributions=param_grid,
    n_iter=20,
    cv=5,
    scoring="f1",
    random_state=42,
    n_jobs=-1,
    verbose=2
)

#### train

In [18]:
random_search.fit(X_train, y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits

RandomizedSearchCV(cv=5,
                   estimator=Pipeline(steps=[('preprocessor',
                                              ColumnTransformer(remainder='passthrough',
                                                                transformers=[('cat',
                                                                               OneHotEncoder(handle_unknown='ignore'),
                                                                               ['sex',
                                                                                'location'])])),
                                             ('classifier',
                                              RandomForestClassifier(random_state=42))]),
                   n_iter=20, n_jobs=-1,
                   param_distributions={'classifier__max_depth': [None, 5, 10,
                                                                  20, 30],
                                        'classifier__max_features': ['sqrt',
                                                                     'log2'],
                                        'classifier__min_samples_leaf': [1, 2,
                                                                         4],
                                        'classifier__min_samples_split': [2, 5,
                                                                          10],
                                        'classifier__n_estimators': [100, 200,
                                                                     300,
                                                                     500]},
                   random_state=42, scoring='f1', verbose=2)

#### best parameter

In [19]:
print("Best Parameters:")
print(random_search.best_params_)

print("\nBest CV Score:")
print(random_search.best_score_)

Best Parameters:
{'classifier__n_estimators': 300, 'classifier__min_samples_split': 5, 'classifier__min_samples_leaf': 1, 'classifier__max_features': 'log2', 'classifier__max_depth': None}

Best CV Score:
0.9947949654098152

#### evaluate tunned model

In [20]:
best_model = random_search.best_estimator_

y_pred_tuned = best_model.predict(X_test)

print(classification_report(
    y_test,
    y_pred_tuned
))

              precision    recall  f1-score   support

           0       1.00      0.98      0.99       306
           1       0.99      1.00      1.00       694

    accuracy                           0.99      1000
   macro avg       1.00      0.99      0.99      1000
weighted avg       0.99      0.99      0.99      1000

#### create comparison table

In [21]:
comparison = pd.DataFrame({
    "Model": ["Baseline RF", "Tuned RF"],
    "Accuracy": [
        accuracy_score(y_test, y_pred),
        accuracy_score(y_test, y_pred_tuned)
    ],
    "F1": [
        f1_score(y_test, y_pred),
        f1_score(y_test, y_pred_tuned)
    ]
})

comparison

         Model  Accuracy        F1
0  Baseline RF     0.993  0.994982
1     Tuned RF     0.994  0.995696

In [22]:
import joblib
import os

os.makedirs("../models", exist_ok=True)

joblib.dump(
    best_model,
    "../models/malaria_diagnosis_rf.pkl"
)

['../models/malaria_diagnosis_rf.pkl']